### ISSUE TITLE
Crash in Creative Inventory

### ISSUE THREAD

**Issue by Quadrum1** [Strobel273/InventiveInventory#21]
**Mod Version & Minecraft Version**
Inventive Inventory 0.4.0 on Minecraft 1.20.2

**Describe the bug**
Opening the creative inventory (the chest icon) instantly crashes the game.

**To Reproduce**
1. Go into creative mode
2. Open inventory
3. Click on  the "Survival Inventory" tab on the bottom right
4. Experience the crash

**Expected behavior**
The game should not crash.

**Additional context**

The Crashlog contains the issue:
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 47
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.method_7611(class_1703.java:287)
	at net.strobel.inventive_inventory.features.automatic_refilling.AutomaticRefillingHandler.captureCurrentState(AutomaticRefillingHandler.java:35)
```

**Comment by Quadrum1** [comment]
Hey, thanks for the quick response!

I was using it in survival as intended, and only noticed this error while designing something there.
Great to see it fixed!

Cheers
